package src.train.common.recipes;

import java.util.ArrayList;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.oredict.OreDictionary;
import src.train.common.api.crafting.ITierCraftingManager;
import src.train.common.core.managers.TierRecipeManager;
import src.train.common.library.ItemData;

public class AssemblyTableRecipes {

	//private static ItemStack ingotSteel = new ItemStack(ItemData.steel.item);
	private static ItemStack ingotIron = new ItemStack(Items.iron_ingot);

	public static void recipes() {

		ITierCraftingManager cm = TierRecipeManager.getInstance();

		ArrayList<ItemStack> ingotSteel = OreDictionary.getOres("ingotSteel");
		if (ingotSteel != null && ingotSteel.size() >= 0) {
			for (int k = 0; k < ingotSteel.size(); k++) {

				//=================== TIER I ===================//
				cm.addRecipe(1, null, new ItemStack(ItemData.woodenBogie.item, 2), new ItemStack(ItemData.woodenFrame.item, 1), new ItemStack(Items.stick, 1), new ItemStack(ItemData.ironChimney.item, 1), null, new ItemStack(ItemData.ironBoiler.item, 1), new ItemStack(ItemData.ironFirebox.item, 1), null, null, new ItemStack(ItemData.minecartLocoCherepanov.item, 1), 1);
				cm.addRecipe(1, new ItemStack(Blocks.crafting_table, 1), new ItemStack(ItemData.woodenBogie.item, 2), new ItemStack(ItemData.woodenFrame.item, 1), new ItemStack(Items.stick, 2), null, new ItemStack(ItemData.woodenCab.item, 1), null, null, new ItemStack(Blocks.furnace, 1), null, new ItemStack(ItemData.minecartWork.item, 1), 1);
				cm.addRecipe(1, null, new ItemStack(ItemData.woodenBogie.item, 2), new ItemStack(ItemData.woodenFrame.item, 1), new ItemStack(Items.stick, 2), null, null, null, null, new ItemStack(Items.coal, 1), null, new ItemStack(ItemData.minecartTender.item, 1), 1);
				cm.addRecipe(1, new ItemStack(Items.iron_ingot, 6), new ItemStack(ItemData.woodenBogie.item, 2), new ItemStack(ItemData.woodenFrame.item, 2), new ItemStack(Items.stick, 2), null, null, null, null, new ItemStack(Items.lava_bucket, 1), null, new ItemStack(ItemData.minecartWatertransp.item, 1), 1);
				cm.addRecipe(1, null, new ItemStack(ItemData.ironBogie.item, 3), new ItemStack(ItemData.ironFrame.item, 2), new ItemStack(ingotIron.getItem(), 2), new ItemStack(ItemData.ironChimney.item, 1), new ItemStack(ItemData.ironCab.item, 1), new ItemStack(ItemData.ironBoiler.item, 2), new ItemStack(ItemData.ironFirebox.item, 1), new ItemStack(Items.water_bucket, 1), new ItemStack(Items.dye, 1, 2), new ItemStack(ItemData.minecartLocoBR80_DB.item, 1), 1);
				cm.addRecipe(1, null, new ItemStack(ItemData.ironBogie.item, 3), new ItemStack(ItemData.ironFrame.item, 2), new ItemStack(ingotIron.getItem(), 2), new ItemStack(ItemData.ironChimney.item, 1), new ItemStack(ItemData.ironCab.item, 1), new ItemStack(ItemData.ironBoiler.item, 2), new ItemStack(ItemData.ironFirebox.item, 1), new ItemStack(Items.coal, 1), null, new ItemStack(ItemData.minecartLocoSteamShay.item, 1), 1);
				cm.addRecipe(1, null, new ItemStack(ItemData.ironBogie.item, 3), new ItemStack(ItemData.ironFrame.item, 2), new ItemStack(ingotIron.getItem(), 2), new ItemStack(ItemData.ironChimney.item, 1), new ItemStack(ItemData.ironCab.item, 1), new ItemStack(ItemData.ironBoiler.item, 2), new ItemStack(ItemData.ironFirebox.item, 1), new ItemStack(Items.coal, 1), new ItemStack(Items.dye, 1, 1), new ItemStack(ItemData.minecartLocoForneyRed.item, 1), 1);
				cm.addRecipe(1, null, new ItemStack(ItemData.ironBogie.item, 2), new ItemStack(ItemData.woodenFrame.item, 1), new ItemStack(Items.stick, 2), null, null, null, null, new ItemStack(Items.coal, 1), new ItemStack(Items.dye, 1, 1), new ItemStack(ItemData.minecartSteamRedTender.item, 1), 1);
				cm.addRecipe(1, null, new ItemStack(ItemData.ironBogie.item, 3), new ItemStack(ItemData.woodenFrame.item, 2), new ItemStack(Items.stick, 2), new ItemStack(ItemData.ironChimney.item, 1), new ItemStack(ItemData.woodenCab.item, 1), new ItemStack(ItemData.ironBoiler.item, 1), new ItemStack(ItemData.ironFirebox.item, 1), null, new ItemStack(Items.dye, 1, 1), new ItemStack(ItemData.minecartPower.item, 1), 1);
				cm.addRecipe(1, null, new ItemStack(ItemData.woodenBogie.item, 2), new ItemStack(ItemData.woodenFrame.item, 2), new ItemStack(Items.stick, 2), new ItemStack(ItemData.ironChimney.item, 1), new ItemStack(ItemData.woodenCab.item, 1), new ItemStack(ItemData.ironBoiler.item, 1), new ItemStack(ItemData.ironFirebox.item, 1), new ItemStack(Blocks.torch, 1), new ItemStack(Items.dye, 1, 4), new ItemStack(ItemData.minecartLoco3.item, 1), 1);
				//cm.addRecipe(1, new ItemStack(Block.planks, 4), new ItemStack(ItemData.ironBogie.item.item, 2), new ItemStack(ItemData.woodenFrame.item.item, 1), new ItemStack(ingotIron.getItem(), 1), null, new ItemStack(ItemData.woodenCab.item.item, 1), null, new ItemStack(ItemData.electmotor.item.item, 2), new ItemStack(Item.redstone, 4), null, new ItemStack(ItemData.minecartTramWood.item, 1), 1);
				cm.addRecipe(1, new ItemStack(ingotIron.getItem(), 2), new ItemStack(ItemData.ironBogie.item, 2), new ItemStack(ItemData.ironFrame.item, 1), new ItemStack(ingotIron.getItem(), 2), null, null, null, null, new ItemStack(Blocks.chest, 1), new ItemStack(Items.dye, 1, 11), new ItemStack(ItemData.minecartMineTrain.item, 1), 1);
				cm.addRecipe(1, new ItemStack(ingotIron.getItem(), 2), new ItemStack(ItemData.ironBogie.item, 2), new ItemStack(ItemData.ironFrame.item, 1), new ItemStack(ingotIron.getItem(), 1), null, new ItemStack(ItemData.controls.item, 1), new ItemStack(ItemData.transformer.item, 1), new ItemStack(ItemData.electmotor.item, 2), new ItemStack(Items.redstone, 1), new ItemStack(Items.dye, 1, 11), new ItemStack(ItemData.minecartLocoMineTrain.item, 1), 1);

				//=================== TIER II ==================//

				cm.addRecipe(2, new ItemStack(ItemData.controls.item, 2), new ItemStack(ItemData.bogie.item, 3), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.steelchimney.item, 1), new ItemStack(ItemData.steelcab.item, 1), new ItemStack(ItemData.electmotor.item, 4), new ItemStack(ItemData.dieselengine.item, 4), new ItemStack(ItemData.generator.item, 2), new ItemStack(Items.dye, 1, 11), new ItemStack(ItemData.minecartCD742.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ItemData.controls.item, 1), new ItemStack(ItemData.bogie.item, 4), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.steelchimney.item, 1), new ItemStack(ItemData.steelcab.item, 1), new ItemStack(ItemData.transmition.item, 1), new ItemStack(ItemData.dieselengine.item, 3), null, new ItemStack(Items.dye, 1, 4), new ItemStack(ItemData.minecartShunter.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ItemData.controls.item, 1), new ItemStack(ItemData.bogie.item, 3), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.steelchimney.item, 1), new ItemStack(ItemData.steelcab.item, 1), new ItemStack(ItemData.electmotor.item, 2), new ItemStack(ItemData.dieselengine.item, 2), new ItemStack(ItemData.generator.item, 2), new ItemStack(Items.dye, 1, 2), new ItemStack(ItemData.minecartChmE3.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ItemData.controls.item, 2), new ItemStack(ItemData.bogie.item, 3), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.steelchimney.item, 1), new ItemStack(ItemData.steelcab.item, 1), new ItemStack(ItemData.electmotor.item, 4), new ItemStack(ItemData.dieselengine.item, 4), new ItemStack(ItemData.generator.item, 3), new ItemStack(Items.dye, 1, 1), new ItemStack(ItemData.minecartGP7Red.item, 1), 1);
				cm.addRecipe(2, null, new ItemStack(ItemData.bogie.item, 3), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.steelchimney.item, 1), new ItemStack(ItemData.steelcab.item, 1), new ItemStack(ItemData.boiler.item, 2), new ItemStack(ItemData.firebox.item, 1), null, null, new ItemStack(ItemData.minecartLocoBR01_DB.item, 1), 1);
				cm.addRecipe(2, null, new ItemStack(ItemData.bogie.item, 3), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.steelchimney.item, 1), new ItemStack(ItemData.steelcab.item, 1), new ItemStack(ItemData.boiler.item, 3), new ItemStack(ItemData.firebox.item, 1), null, null, new ItemStack(ItemData.minecartLocoC62Class.item, 1), 1);
				cm.addRecipe(2, null, new ItemStack(ItemData.bogie.item, 3), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.steelchimney.item, 1), new ItemStack(ItemData.steelcab.item, 1), new ItemStack(ItemData.boiler.item, 2), new ItemStack(ItemData.firebox.item, 1), null, new ItemStack(Items.dye, 1, 4), new ItemStack(ItemData.minecartLocomogulBlue.item, 1), 1);
				//cm.addRecipe(2, null, new ItemStack(ItemData.bogie.item.item, 3), new ItemStack(ItemData.steelframe.item.item, 4), new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.steelchimney.item.item, 1), new ItemStack(ItemData.steelcab.item.item, 1), new ItemStack(ItemData.boiler.item.item, 4), new ItemStack(ItemData.firebox.item.item, 2), null, null, new ItemStack(ItemData.minecartLoco4.item, 1), 1);
				//cm.addRecipe(2, null, new ItemStack(ItemData.bogie.item.item, 3), new ItemStack(ItemData.steelframe.item.item, 3), new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.steelchimney.item.item, 1), new ItemStack(ItemData.steelcab.item.item, 1), new ItemStack(ItemData.boiler.item.item, 3), new ItemStack(ItemData.firebox.item.item, 2), null, null, new ItemStack(ItemData.minecartHeavySteam.item, 1), 1);//TODO put it back once Heavy Steam is back
				cm.addRecipe(2, new ItemStack(ingotSteel.get(k).getItem(), 6), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 3), new ItemStack(ingotSteel.get(k).getItem(), 1), new ItemStack(ItemData.steelchimney.item, 1), null, new ItemStack(ItemData.boiler.item, 1), new ItemStack(ItemData.firebox.item, 1), new ItemStack(Blocks.rail, 16), null, new ItemStack(ItemData.minecartBuilder.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, new ItemStack(ItemData.steelcab.item, 1), null, null, new ItemStack(ItemData.seats.item, 1), new ItemStack(Items.dye, 1, 2), new ItemStack(ItemData.minecartPassenger5.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ingotSteel.get(k).getItem(), 6), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, null, null, new ItemStack(ItemData.minecartFlatCartSU.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ingotSteel.get(k).getItem(), 6), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Items.water_bucket, 1), new ItemStack(Items.dye, 1, 11), new ItemStack(ItemData.minecartTankWagon.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ingotSteel.get(k).getItem(), 6), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Items.water_bucket, 1), new ItemStack(Items.dye, 1, 8), new ItemStack(ItemData.minecartTankWagon2.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ingotSteel.get(k).getItem(), 5), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Blocks.chest, 1), null, new ItemStack(ItemData.minecartBoxCartUS.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ingotSteel.get(k).getItem(), 5), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Items.wheat, 3), null, new ItemStack(ItemData.minecartFreightHopperUS.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ingotSteel.get(k).getItem(), 6), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Items.water_bucket, 1), null, new ItemStack(ItemData.minecartTankWagonUS.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ingotSteel.get(k).getItem(), 6), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Items.coal, 1), null, new ItemStack(ItemData.minecartTenderBR01_DB.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ingotSteel.get(k).getItem(), 6), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Items.coal, 1), null, new ItemStack(ItemData.minecartTenderC62Class.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, new ItemStack(ItemData.steelcab.item, 1), null, null, new ItemStack(ItemData.seats.item, 1), new ItemStack(Items.dye, 1, 3), new ItemStack(ItemData.minecartPassenger8_1class_DB.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, new ItemStack(ItemData.steelcab.item, 1), null, null, new ItemStack(ItemData.seats.item, 1), new ItemStack(Items.dye, 1, 2), new ItemStack(ItemData.minecartPassenger9_2class_DB.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ingotSteel.get(k).getItem(), 5), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Blocks.chest, 1), null, new ItemStack(ItemData.minecartFreightWagon_DB.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ingotSteel.get(k).getItem(), 5), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Blocks.chest, 1), null, new ItemStack(ItemData.minecartMailWagon_DB.item, 1), 1);
				cm.addRecipe(2, null, new ItemStack(ItemData.bogie.item, 3), new ItemStack(ItemData.steelframe.item, 3), new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.steelchimney.item, 2), new ItemStack(ItemData.steelcab.item, 1), new ItemStack(ItemData.boiler.item, 3), new ItemStack(ItemData.firebox.item, 2), null, null, new ItemStack(ItemData.minecartLocoEr.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ingotSteel.get(k).getItem(), 6), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 3), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Items.coal, 1), null, new ItemStack(ItemData.minecartTenderEr.item, 1), 1);
				cm.addRecipe(2, new ItemStack(ItemData.controls.item,1), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 1), new ItemStack(ingotSteel.get(k).getItem(), 1), null, new ItemStack(ItemData.steelcab.item, 1), new ItemStack(ItemData.transformer.item,2), new ItemStack(ItemData.electmotor.item, 2), new ItemStack(Items.redstone, 4), null, new ItemStack(ItemData.minecartNYTram.item, 1), 1);
				cm.addRecipe(2, null, new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 1), new ItemStack(ingotSteel.get(k).getItem(), 1), null, new ItemStack(ItemData.steelcab.item, 1), null, null, null, null, new ItemStack(ItemData.minecartPassengerTramNY.item, 1), 1);
				//=================== TIER III =================//

				cm.addRecipe(3, new ItemStack(ItemData.controls.item, 1), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 1), new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.steelchimney.item, 1), new ItemStack(ItemData.steelcab.item, 1), new ItemStack(ItemData.transmition.item, 1), new ItemStack(ItemData.dieselengine.item, 2), null, new ItemStack(Items.dye, 1, 1), new ItemStack(ItemData.minecartKof_DB.item, 1), 1);
				cm.addRecipe(3, new ItemStack(ItemData.controls.item, 1), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.steelchimney.item, 1), new ItemStack(ItemData.steelcab.item, 1), new ItemStack(ItemData.transmition.item, 1), new ItemStack(ItemData.dieselengine.item, 3), null, new ItemStack(Items.dye, 1, 1), new ItemStack(ItemData.minecartV60_DB.item, 1), 1);
				cm.addRecipe(3, new ItemStack(ItemData.controls.item,2), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 1), new ItemStack(ingotSteel.get(k).getItem(), 1), null, new ItemStack(ItemData.steelcab.item, 1), new ItemStack(ItemData.transformer.item,2), new ItemStack(ItemData.electmotor.item, 2), new ItemStack(Items.redstone, 4), null, new ItemStack(ItemData.minecartLocoHighSpeedZeroED.item, 1), 1);
				cm.addRecipe(3, new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, new ItemStack(ItemData.steelcab.item, 1), null, new ItemStack(ItemData.seats.item, 5), null, null, new ItemStack(ItemData.minecartPassengerHighSpeedCarZeroED.item, 1), 1);
				//cm.addRecipe(3, new ItemStack(ItemData.controls.item.item,3), new ItemStack(ItemData.bogie.item.item, 2), new ItemStack(ItemData.steelframe.item.item, 1), new ItemStack(ingotSteel.get(k).getItem(), 1), null, new ItemStack(ItemData.steelcab.item.item, 1), new ItemStack(ItemData.transformer.item.item,4), new ItemStack(ItemData.electmotor.item.item, 4), new ItemStack(Item.redstone, 4), new ItemStack(Item.dyePowder, 1, 8), new ItemStack(ItemData.minecartNewHighSpeedLoco.item, 1), 1);
				cm.addRecipe(3, new ItemStack(ItemData.controls.item, 2), new ItemStack(ItemData.bogie.item, 3), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 1), new ItemStack(ItemData.steelchimney.item, 1), new ItemStack(ItemData.steelcab.item, 1), new ItemStack(ItemData.transformer.item, 2), new ItemStack(ItemData.electmotor.item, 2), new ItemStack(Items.redstone, 2), new ItemStack(Items.dye, 1, 2), new ItemStack(ItemData.minecartVL10.item, 1), 1);
				cm.addRecipe(3, new ItemStack(ItemData.controls.item, 2), new ItemStack(ItemData.bogie.item, 3), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 1), new ItemStack(ItemData.steelchimney.item, 1), new ItemStack(ItemData.steelcab.item, 1), new ItemStack(ItemData.transformer.item, 2), new ItemStack(ItemData.electmotor.item, 2), new ItemStack(Items.redstone, 2), new ItemStack(Items.dye, 1, 2), new ItemStack(ItemData.minecartBR_E69.item, 1), 1);
				cm.addRecipe(3, new ItemStack(ItemData.controls.item, 2), new ItemStack(ItemData.bogie.item, 3), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.steelchimney.item, 1), new ItemStack(ItemData.steelcab.item, 1), new ItemStack(ItemData.electmotor.item, 6), new ItemStack(ItemData.dieselengine.item, 6), new ItemStack(ItemData.generator.item, 4), new ItemStack(Items.dye, 1, 14), new ItemStack(ItemData.minecartLocoSD70.item, 1), 1);
				cm.addRecipe(3, new ItemStack(ItemData.controls.item,2), new ItemStack(ItemData.bogie.item, 3), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), new ItemStack(ItemData.steelchimney.item, 1), new ItemStack(ItemData.steelcab.item, 1), new ItemStack(ItemData.electmotor.item,6), new ItemStack(ItemData.dieselengine.item, 6), new ItemStack(ItemData.generator.item,4), new ItemStack(Items.dye, 1, 1), new ItemStack(ItemData.minecartLocoSD40.item, 1), 1);
				cm.addRecipe(3, new ItemStack(ingotSteel.get(k).getItem(), 5), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Blocks.chest, 1), null, new ItemStack(ItemData.minecartOpenWagon.item, 1), 1);
				cm.addRecipe(3, new ItemStack(ingotSteel.get(k).getItem(), 5), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Blocks.jukebox, 1), null, new ItemStack(ItemData.minecartJukeBoxCart.item, 1), 1);
				cm.addRecipe(3, new ItemStack(ingotSteel.get(k).getItem(), 5), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, new ItemStack(ItemData.steelcab.item, 1), null, new ItemStack(ItemData.seats.item, 1), null, new ItemStack(Items.dye, 1, 4), new ItemStack(ItemData.minecartPassengerBlue.item, 1), 1);
				cm.addRecipe(3, new ItemStack(ingotSteel.get(k).getItem(), 5), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Blocks.rail, 1), null, new ItemStack(ItemData.minecartFlatCartRail_DB.item, 1), 1);
				cm.addRecipe(3, new ItemStack(ingotSteel.get(k).getItem(), 5), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, null, null, new ItemStack(ItemData.minecartFlatCart_DB.item, 1), 1);
				cm.addRecipe(3, new ItemStack(ingotSteel.get(k).getItem(), 5), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Blocks.chest, 1), null, new ItemStack(ItemData.minecartFreightGondola_DB.item, 1), 1);
				cm.addRecipe(3, new ItemStack(ingotSteel.get(k).getItem(), 5), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Items.water_bucket, 1), null, new ItemStack(ItemData.minecartTankWagon_DB.item, 1), 1);
				cm.addRecipe(3, new ItemStack(ingotSteel.get(k).getItem(), 5), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Blocks.chest, 1), new ItemStack(Items.dye, 1, 7), new ItemStack(ItemData.minecartFreightTrailer.item, 1), 1);
				cm.addRecipe(3, new ItemStack(ingotSteel.get(k).getItem(), 5), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Blocks.chest, 2), new ItemStack(Items.dye, 1, 1), new ItemStack(ItemData.minecartFreightWellcar.item, 1), 1);

				ArrayList<ItemStack> s1 = OreDictionary.getOres("plankWood");
				ArrayList<ItemStack> s2 = OreDictionary.getOres("logWood");
				if (s1 != null && s1.size() >= 0) {
					for (int i = 0; i < s1.size(); i++) {
						if (s2 != null && s2.size() >= 0) {
							for (int j = 0; j < s2.size(); j++) {
								cm.addRecipe(1, new ItemStack(s1.get(i).getItem(), 6, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.woodenBogie.item, 2), new ItemStack(ItemData.woodenFrame.item, 2), new ItemStack(Items.stick, 2), null, null, null, null, new ItemStack(s2.get(j).getItem(), 1, OreDictionary.WILDCARD_VALUE), null, new ItemStack(ItemData.minecartWood.item, 1), 1);
								cm.addRecipe(2, new ItemStack(s1.get(i).getItem(), 3, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 1), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(s2.get(j).getItem(), 1, OreDictionary.WILDCARD_VALUE), null, new ItemStack(ItemData.minecartFreightWood2.item, 1), 1);
								cm.addRecipe(2, new ItemStack(s1.get(i).getItem(), 6, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(s1.get(i).getItem(), 1, OreDictionary.WILDCARD_VALUE), null, new ItemStack(ItemData.minecartFreightCenterBeam_Wood_1.item, 1), 1);
								cm.addRecipe(2, new ItemStack(s1.get(i).getItem(), 6, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(s1.get(i).getItem(), 4, OreDictionary.WILDCARD_VALUE), null, new ItemStack(ItemData.minecartFlatCartWoodUS.item, 1), 1);
								cm.addRecipe(2, new ItemStack(s1.get(i).getItem(), 6, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(s1.get(i).getItem(), 1, OreDictionary.WILDCARD_VALUE), null, new ItemStack(ItemData.minecartFreightCenterBeam_Wood_2.item, 1), 1);
								cm.addRecipe(3, new ItemStack(ingotSteel.get(k).getItem(), 5), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(s2.get(j).getItem(), 1, OreDictionary.WILDCARD_VALUE), null, new ItemStack(ItemData.minecartFlatCartLogs_DB.item, 1), 1);
								cm.addRecipe(1, new ItemStack(s1.get(i).getItem(), 8, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.woodenBogie.item, 3), new ItemStack(ItemData.woodenFrame.item, 2), new ItemStack(ingotIron.getItem(), 2), new ItemStack(ItemData.ironChimney.item, 1), null, new ItemStack(ItemData.ironBoiler.item, 1), new ItemStack(ItemData.ironFirebox.item, 1), new ItemStack(Items.gold_ingot, 2), new ItemStack(Items.dye, 1, 2), new ItemStack(ItemData.minecartLocoSteamAdler.item, 1), 1);
								cm.addRecipe(1, new ItemStack(ingotIron.getItem(), 2), new ItemStack(ItemData.woodenBogie.item, 2), new ItemStack(ItemData.woodenFrame.item, 1), new ItemStack(ingotIron.getItem(), 1), null, null, null, null, new ItemStack(Items.coal, 1), new ItemStack(Items.dye, 1, 2), new ItemStack(ItemData.minecartTenderAdler.item, 1), 1);
								cm.addRecipe(1, new ItemStack(ingotIron.getItem(), 1), new ItemStack(ItemData.woodenBogie.item, 2), new ItemStack(ItemData.woodenFrame.item, 2), new ItemStack(ingotIron.getItem(), 1), null, new ItemStack(ItemData.woodenCab.item, 1), null, null, new ItemStack(ItemData.seats.item, 1), new ItemStack(Items.dye, 1, 11), new ItemStack(ItemData.minecartPassengerAdler.item, 1), 1);
							}
						}
						//=================== TIER I ===================//
						cm.addRecipe(1, new ItemStack(s1.get(i).getItem(), 6, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.woodenBogie.item, 2), new ItemStack(ItemData.woodenFrame.item, 2), new ItemStack(Items.stick, 2), null, new ItemStack(ItemData.woodenCab.item, 1), null, null, new ItemStack(ItemData.seats.item, 1), null, new ItemStack(ItemData.minecartPassenger2.item, 1), 1);
						cm.addRecipe(1, new ItemStack(s1.get(i).getItem(), 6, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.woodenBogie.item, 2), new ItemStack(ItemData.woodenFrame.item, 2), new ItemStack(Items.stick, 2), null, new ItemStack(ItemData.woodenCab.item, 1), null, null, new ItemStack(ItemData.seats.item, 1), null, new ItemStack(ItemData.minecartCaboose.item, 1), 1);
						cm.addRecipe(1, new ItemStack(s1.get(i).getItem(), 6, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.woodenBogie.item, 2), new ItemStack(ItemData.woodenFrame.item, 2), new ItemStack(Items.stick, 2), null, null, null, null, new ItemStack(Blocks.chest, 1), null, new ItemStack(ItemData.minecartFreightCartSmall.item, 1), 1);
						cm.addRecipe(1, new ItemStack(s1.get(i).getItem(), 3, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.woodenBogie.item, 2), new ItemStack(ItemData.woodenFrame.item, 2), new ItemStack(Items.stick, 2), null, null, null, null, null, null, new ItemStack(ItemData.minecartFlatCart.item, 1), 1);
						cm.addRecipe(1, new ItemStack(s1.get(i).getItem(), 3, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.woodenBogie.item, 2), new ItemStack(ItemData.woodenFrame.item, 2), new ItemStack(ingotIron.getItem(), 1), null, null, null, null, new ItemStack(Blocks.crafting_table, 1), new ItemStack(Items.dye, 1, 1), new ItemStack(ItemData.minecartCabooseLogging.item, 1), 1);
						cm.addRecipe(1, new ItemStack(s1.get(i).getItem(), 6, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.ironBogie.item, 2), new ItemStack(ItemData.ironFrame.item, 2), new ItemStack(ingotIron.getItem(), 2), null, null, null, null, new ItemStack(Blocks.chest, 2), null, new ItemStack(ItemData.minecartChest.item, 1), 1);
						cm.addRecipe(1, new ItemStack(s1.get(i).getItem(), 6, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.ironBogie.item, 2), new ItemStack(ItemData.ironFrame.item, 2), new ItemStack(ingotIron.getItem(), 2), null, null, null, null, new ItemStack(Blocks.chest, 2), null, new ItemStack(ItemData.minecartFreightCart2.item, 1), 1);
						cm.addRecipe(1, new ItemStack(s1.get(i).getItem(), 6, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.ironBogie.item, 2), new ItemStack(ItemData.ironFrame.item, 2), new ItemStack(ingotIron.getItem(), 2), null, null, null, null, new ItemStack(Blocks.chest, 2), null, new ItemStack(ItemData.minecartFreightCartUS.item, 1), 1);
						cm.addRecipe(1, new ItemStack(s1.get(i).getItem(), 4, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.ironBogie.item, 2), new ItemStack(ItemData.ironFrame.item, 4), new ItemStack(ingotIron.getItem(), 2), null, null, null, null, new ItemStack(Blocks.chest, 1), null, new ItemStack(ItemData.minecartFreightClosed.item, 1), 1);
						cm.addRecipe(1, new ItemStack(s1.get(i).getItem(), 2, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.ironBogie.item, 2), new ItemStack(ItemData.ironFrame.item, 2), new ItemStack(ingotIron.getItem(), 2), null, null, null, null, new ItemStack(Blocks.chest, 2), null, new ItemStack(ItemData.minecartFreightOpen2.item, 1), 1);
						cm.addRecipe(1, new ItemStack(s1.get(i).getItem(), 2, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.ironBogie.item, 2), new ItemStack(ItemData.ironFrame.item, 2), new ItemStack(ingotIron.getItem(), 2), null, new ItemStack(ItemData.woodenCab.item, 1), null, null, new ItemStack(ItemData.seats.item, 1), null, new ItemStack(ItemData.minecartCaboose3.item, 1), 1);
						cm.addRecipe(1, new ItemStack(s1.get(i).getItem(), 2, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.ironBogie.item, 2), new ItemStack(ItemData.ironFrame.item, 2), new ItemStack(ingotIron.getItem(), 2), null, new ItemStack(ItemData.ironCab.item, 1), null, null, new ItemStack(ItemData.seats.item, 1), null, new ItemStack(ItemData.minecartPassenger7.item, 1), 1);
						cm.addRecipe(1, new ItemStack(s1.get(i).getItem(), 4, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.ironBogie.item, 2), new ItemStack(ItemData.woodenFrame.item, 1), new ItemStack(ingotIron.getItem(), 1), null, new ItemStack(ItemData.woodenCab.item, 1), new ItemStack(ItemData.transformer.item, 1), new ItemStack(ItemData.electmotor.item, 2), new ItemStack(Items.redstone, 4), null, new ItemStack(ItemData.minecartTramWood.item, 1), 1);
						//=================== TIER II ==================//
						cm.addRecipe(2, new ItemStack(s1.get(i).getItem(), 6, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Blocks.crafting_table, 1), new ItemStack(Items.dye, 1, 1), new ItemStack(ItemData.minecartCabooseWork.item, 1), 1);
						cm.addRecipe(2, new ItemStack(s1.get(i).getItem(), 6, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, new ItemStack(Items.leather, 1), null, new ItemStack(ItemData.minecartStockCar.item, 1), 1);
						cm.addRecipe(2, new ItemStack(s1.get(i).getItem(), 3, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, null, null, new ItemStack(ItemData.minecartFlatCartUS.item, 1), 1);
						cm.addRecipe(2, new ItemStack(s1.get(i).getItem(), 6, OreDictionary.WILDCARD_VALUE), new ItemStack(ItemData.bogie.item, 2), new ItemStack(ItemData.steelframe.item, 2), new ItemStack(ingotSteel.get(k).getItem(), 2), null, null, null, null, null, null, new ItemStack(ItemData.minecartFreightCenterBeam_Empty.item, 1), 1);
					}
				}
			}
		}
	}
}